pipeline {
    agent any

    stages {
        stage('Check Environment') {
            steps {
                sh 'whoami'
                sh 'hostname'
                sh 'docker --version'
                sh 'docker ps'
            }
        }

        stage('Run Node Container') {
            steps {
                sh 'docker run --rm node:16-alpine node --version'
            }
        }
    }
}
