pipeline {
    agent none

    stages {
        stage('Test in Docker on EC2 Agent') {
            agent {
                label 'ec2'
            }
            steps {
                sh 'whoami'
                sh 'hostname'
                sh 'docker ps'
                sh 'docker run --rm node:16-alpine node --version'
            }
        }
    }
}
